### ISSUE TITLE
Would you accept to support java 1.6?

### ISSUE THREAD

**Issue by tonivdv** [CleverCloud/rabbitmq-autoreconnect-java#1]
Hey,

First of all thanks for this library. However I would need this to be compatible with 1.6 ... Which means changing just a couple of lines.

Would you agree to lower the compatibility level?

**Comment by Keruspe** [comment]
Hi,

We usually only work with java7 but I see no harm in supporting java6 too.

I have a few bugfixes wip for next release, feel free to send us à pull
request if you also want java6 support in it

**Comment by tonivdv** [comment]
Okay great! You can expect it soon :)
